#
# Module manifest for module 'MFARunner'
#
# Generated by: leca

#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\MFARunner.psm1'

# Version number of this module.
ModuleVersion = '0.5.0'

# Supported PSEditions
# CompatiblePSEditions = @()


# Author of this module
Author = 'Antoine Lecompte'

CompanyName = "Natrix Technologies"

# Copyright statement for this module
Copyright = '(c) Antoine Lecompte | Natrix Technologies. All rights Reserved'

# Description of the functionality provided by this module
Description = 'This module provides functionality to automate MFA appointment enrollment for microsoft partners'


# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @("*")

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @("*")

# Variables to export from this module
VariablesToExport = '*'

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/alecompte/MFARunner'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

